/* Copyright (C) 2013-2026 Christian Fischbach <cf@cflib.de>
 *
 * This file is part of cflib.
 *
 * Licensed under the MIT License.
 */

#include <cflib/serialize/generate/apidoc.h>
#include <cflib/serialize/generate/cppremoteservices.h>
#include <cflib/serialize/generate/javascript.h>
#include <cflib/serialize/generate/python.h>
#include <cflib/serialize/headerparser.h>
#include <cflib/serialize/structuredtypeinfos.h>
#include <cflib/util/cmdline.h>
#include <cflib/util/log.h>

#include <iostream>

using namespace cflib::serialize;
using namespace cflib::serialize::generate;
using namespace cflib::util;

namespace {

auto && err = std::cerr;

const Set<ByteArray> allowedTypes = { "apidoc", "cpp", "javascript", "python" };

int showUsage(const ByteArray & executable)
{
    err << "Usage: " << executable.toStdString() << " -d <dir> -t <type> [-t ...] <headers>"  << std::endl
        << "Options:"                                                       << std::endl
        << "  -h, --help        => this help"                               << std::endl
        << "  -l, --log <level> => set log level 1 -> all, 7 -> off"        << std::endl
        << "  -d, --dest <dir>  => destination dir"                         << std::endl
        << "  -g, --git  <hash> => git hash"                                << std::endl
        << "  -t, --type <type> => type of API to be exported (repeatable)" << std::endl
        << "  -n, --name <name> => name of the service"                     << std::endl
        << "API Types:"                                                     << std::endl
        << "  " << allowedTypes.toList().sorted().join(' ').toStdString()   << std::endl;
    return 1;
}

}

int main(int argc, char *argv[])
{
    CmdLine cmdLine(argc, argv);
    Option help    ('h', "help"                   ); cmdLine << help;
    Option logOpt  ('l', "log",  true             ); cmdLine << logOpt;
    Option destOpt ('d', "dest", true, false      ); cmdLine << destOpt;
    Option gitOpt  ('g', "git",  true             ); cmdLine << gitOpt;
    Option typesOpt('t', "type", true, false, true); cmdLine << typesOpt;
    Option nameOpt ('n', "name", true, false      ); cmdLine << nameOpt;
    Arg    headers (false, true                   ); cmdLine << headers;
    if (!cmdLine.parse() || help.isSet()) return showUsage(cmdLine.executable());

    for (const ByteArray & type : typesOpt.values()) if (!allowedTypes.contains(type)) {
        err << "unknown API type: " << type.toStdString() << std::endl;
        return 1;
    }

    // logging
    Log::start("-");
    if (logOpt.isSet()) Log::setLogLevel(logOpt.value().toUInt());
    else                Log::setLogLevel(LogCat::Warn);

    String name;
    if (nameOpt.isSet()) {
        name = nameOpt.value() + " API";
        if (name[0] >= 97) name[0] -= 32;
    } else name = "API";

    String readme;
    readme <<
        "<!-- ============================================================================ -->\n"
        "<!-- Generated by CFLib                                                           -->\n"
        "<!-- ============================================================================ -->\n"
        "\n"
        "# " << name << "\n"
        "\n"
        "git hash: " << gitOpt.value("-") << "\n";
    File::write(destOpt.value() + "/version.md", readme.toUtf8());

    StructuredTypeInfos infos;
    for (const ByteArray & header : headers.values()) {
        const String content = File::readUtf8(header);
        if (content.isNull()) {
            err << "cannot readfile: " << header.toStdString() << std::endl;
            return 2;
        }
        HeaderParser parser;
        if (!parser.parse(content)) {
            err << "cannot parse file: " << header.toStdString() << " -> " << parser.lastError().str() << std::endl;
            return 3;
        }
        for (const SerializeTypeInfo & info : parser.classes()) infos << info;
        infos.permissions += parser.permissions();
    }

    const SerializeTypeInfos missing = infos.fixPlaceholders();
    if (!missing.isEmpty()) {
        err << "Missing types:" << std::endl;
        for (const SerializeTypeInfo & ti : missing) err << "  " << ti.getName().str() << std::endl;
        return 4;
    }

    for (const ByteArray & type : typesOpt.values()) {
        if      (type == "apidoc"    ) generateAPIDoc           (infos, destOpt.value() + "/apidoc", name);
        else if (type == "cpp"       ) generateCppRemoteServices(infos, destOpt.value() + "/cpp");
        else if (type == "javascript") generateJavaScript       (infos, destOpt.value());
        else                           generatePython           (infos, destOpt.value());
    }

    return 0;
}
