/* Copyright (C) 2013-2026 Christian Fischbach <cf@cflib.de>
 *
 * This file is part of cflib.
 *
 * Licensed under the MIT License.
 */

#include "cppremoteservices.h"

#include <cflib/util/log.h>
#include <cflib/util/util.h>

#include <dirent.h>

using namespace cflib::util;

USE_LOG(LogCat::JS)

namespace cflib::serialize::generate {

namespace {

String signature(const SerializeFunctionTypeInfo & fti, bool isRSig, const String & className = {})
{
    String rv;
    if (isRSig) rv += "sig<";
    if (fti.returnType.isNull()) rv += "void ";
    else rv << fti.returnType.getName() << ' ';
    if (isRSig) rv += "(";
    else {
        if (!className.isEmpty()) rv << className << "::";
        rv << fti.name << '(';
    }
    bool isFirst = true;
    int id = 0;
    for (const SerializeVariableTypeInfo & vti : fti.parameters) {
        if (isFirst) isFirst = false;
        else rv += ", ";
        if (!vti.isRef) rv += "const ";
        rv << vti.type.getName() << " &";
        if (!vti.name.isEmpty()) rv << ' ' << vti.name;
        else if (!className.isEmpty()) rv << " __param_" << String::number(++id);
    }
    rv += ')';
    if (isRSig) rv << "> " << fti.name;
    return rv;
}

String generateImpl(const SerializeTypeInfo & ti, const SerializeFunctionTypeInfo & fti)
{
    CF_UNUSED(ti);

    String rv;

    int id = 0;
    for (const SerializeVariableTypeInfo & vti : fti.parameters) {
        rv << "    CF_UNUSED(";
        if (!vti.name.isEmpty()) rv << vti.name;
        else rv << "__param_" << String::number(++id);
        rv << ");\n";
    }

    if (!fti.returnType.isNull()) rv << "    return {};\n";
    return rv;
}

String generate(const SerializeTypeInfo & ti, bool isHeader)
{
    String cpp;
    cpp <<
        "// ============================================================================\n"
        "// Generated by CFLib\n"
        "// ============================================================================\n"
        "\n";

    if (!isHeader) {
        cpp <<
            "#include \"" << ti.typeName.toLower() << ".h\"\n"
            "\n";
    } else {
        for (const SerializeTypeInfo & cl : ti.allUsedClasses()) {
            cpp << "#include <" << cl.getName().toLower().replace("::", "/") << ".h>\n";
        }
        cpp <<
            "\n"
            "#include <cflib/base.h>\n";
        if (!ti.cfSignals.isEmpty()) {
            cpp << "#include <cflib/util/sig.h>\n";
        }
        cpp << "\n";
    }

    if (!ti.ns.isEmpty()) cpp <<
        "namespace " << ti.ns << " {\n"
        "\n";
    if (isHeader) cpp <<
        "class " << ti.typeName << "\n"
        "{\n"
        "public:\n";

    bool isFirst = true;
    for (const SerializeFunctionTypeInfo & fti : ti.functions) {
        if (isHeader) cpp << "    " << signature(fti, false) << ";\n";
        else {
            if (isFirst) isFirst = false;
            else cpp << "\n";
            cpp <<
                signature(fti, false, ti.typeName) << "\n" <<
                "{\n" <<
                generateImpl(ti, fti) <<
                "}\n";
        }
    }

    if (isHeader) {
        if (!ti.cfSignals.isEmpty()) cpp <<
            "\n"
            "cfsignals:\n";
        for (const SerializeFunctionTypeInfo & fti : ti.cfSignals) {
            if (isHeader) cpp << "    " << signature(fti, true) << ";\n";
        }
    }

    if (isHeader) cpp <<
        "};\n";
    if (!ti.ns.isEmpty()) cpp <<
        "\n"
        "}\n";
    return cpp;
}

}

void generateCppRemoteServices(const StructuredTypeInfos & typeInfos, const String & dest)
{
    // write services
    const String destPath = dest + "/";
    mkPath(destPath);
    Set<String> files;
    for (const SerializeTypeInfo & ti : typeInfos.services()) {
        String header = ti.typeName.toLower();
        String impl = header + ".cpp";
        header += ".h";
        files << header << impl;
        writeFile(destPath + header, generate(ti, true ).toUtf8());
        writeFile(destPath + impl,   generate(ti, false).toUtf8());
    }

    // remove old
    {
        DIR * d = opendir(destPath.c_str());
        if (d) {
            struct dirent * ent;
            while ((ent = readdir(d)) != nullptr) {
                String name(ent->d_name);
                if (name == "." || name == "..") continue;
                if (!files.contains(name)) removeFile(destPath + name);
            }
            closedir(d);
        }
    }
}

}