# Copyright (C) 2013-2026 Christian Fischbach <cf@cflib.de>
#
# This file is part of cflib.
#
# Licensed under the MIT License.

# library
function(cf_lib lib)
    cmake_parse_arguments(ARG "ENABLE_EXCEPTIONS;ENABLE_SER" "PCH" "PUBLIC;PRIVATE;DIRS;RESOURCES;OTHER_FILES;DAO;REMOTE_APIS" ${ARGN})
    if(ARG_REMOTE_APIS)
        set(ARG_ENABLE_SER TRUE)
    endif()

    # sources, libs and general config
    cf_find_sources(sources . ${ARG_DIRS} OTHER_FILES ${ARG_OTHER_FILES})
    if(ONLY_GENERATORS)
        add_library(${lib} EXCLUDE_FROM_ALL ${sources})
    else()
        add_library(${lib} ${sources})
    endif()
    cf_configure_target(${lib} ${ARG_ENABLE_EXCEPTIONS} "${ARG_PCH}" ${ARG_ENABLE_SER} ${ARG_RESOURCES})
    target_include_directories(${lib} PUBLIC "${PROJECT_SOURCE_DIR}")
    target_link_libraries(${lib} PUBLIC ${ARG_PUBLIC} PRIVATE ${ARG_PRIVATE})

    # ARG_DAO and ARG_REMOTE_APIS
    string(REGEX REPLACE "lib$" "" api_name ${lib})
    cf_handle_args_dao_remote_apis(${lib} ${api_name})
endfunction()

# application
function(cf_app app)
    cmake_parse_arguments(ARG "ENABLE_EXCEPTIONS;ENABLE_SER;CF_GENERATOR" "PCH" "DIRS;RESOURCES;OTHER_FILES;DAO;REMOTE_APIS" ${ARGN})
    if(ARG_REMOTE_APIS)
        set(ARG_ENABLE_SER TRUE)
    endif()

    # use compiled generators (cross compile)
    if(ARG_CF_GENERATOR AND GENERATORS_BIN_DIR)
        add_executable(${app} IMPORTED GLOBAL)
        set_property(TARGET ${app} PROPERTY IMPORTED_LOCATION "${GENERATORS_BIN_DIR}/${app}")
        return()
    endif()

    # sources, libs and general config
    cf_find_sources(sources . ${ARG_DIRS} OTHER_FILES ${ARG_OTHER_FILES})
    if(ONLY_GENERATORS AND NOT ARG_CF_GENERATOR)
        add_executable(${app} EXCLUDE_FROM_ALL ${sources})
    else()
        add_executable(${app} ${sources})
    endif()
    cf_configure_target(${app} ${ARG_ENABLE_EXCEPTIONS} "${ARG_PCH}" ${ARG_ENABLE_SER} ${ARG_RESOURCES})
    target_include_directories(${app} PRIVATE .)
    if(ARG_CF_GENERATOR)
        set_target_properties(${app} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/generators")
    else()
        set_target_properties(${app} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin")
    endif()
    target_link_libraries(${app} PRIVATE ${ARG_UNPARSED_ARGUMENTS})

    # ARG_DAO and ARG_REMOTE_APIS
    cf_handle_args_dao_remote_apis(${app} ${app})

    # strip release builds and split debug info
    if(NOT APPLE)
        add_custom_command(TARGET "${app}" POST_BUILD
            COMMAND $<$<CONFIG:Release>:${CMAKE_STRIP}>           ARGS --strip-all $<TARGET_FILE:${app}>
            COMMAND $<$<CONFIG:RelWithDebInfo>:${CMAKE_OBJCOPY}>  ARGS --only-keep-debug $<TARGET_FILE:${app}> $<TARGET_FILE:${app}>.debug
            COMMAND $<$<CONFIG:RelWithDebInfo>:${CMAKE_STRIP}>    ARGS -g $<TARGET_FILE:${app}>
            COMMAND $<$<CONFIG:RelWithDebInfo>:${CMAKE_OBJCOPY}>  ARGS --add-gnu-debuglink=$<TARGET_FILE:${app}>.debug $<TARGET_FILE:${app}>
        )
    endif()
endfunction()

# test
function(cf_test test lib)
    cmake_parse_arguments(ARG "ENABLE_EXCEPTIONS;ENABLE_SER" "PCH" "DIRS;RESOURCES" ${ARGN})

    cf_find_sources(sources . ${ARG_DIRS})
    if(ONLY_GENERATORS)
        add_executable(${test} EXCLUDE_FROM_ALL ${sources})
    else()
        add_executable(${test} ${sources})
    endif()
    cf_configure_target(${test} ${ARG_ENABLE_EXCEPTIONS} "${ARG_PCH}" ${ARG_ENABLE_SER} ${ARG_RESOURCES})
    target_link_libraries(${test} PRIVATE ${lib} cflib_testmain)
    doctest_discover_tests(${test})
endfunction()

function(cf_test_old test lib)
    cmake_parse_arguments(ARG "ENABLE_EXCEPTIONS;ENABLE_SER" "PCH" "DIRS;RESOURCES" ${ARGN})

    cf_find_sources(sources . ${ARG_DIRS})
    if(ONLY_GENERATORS)
        add_executable(${test} EXCLUDE_FROM_ALL ${sources})
    else()
        add_executable(${test} ${sources})
    endif()
    cf_configure_target(${test} ${ARG_ENABLE_EXCEPTIONS} "${ARG_PCH}" ${ARG_ENABLE_SER} ${ARG_RESOURCES})
    target_link_libraries(${test} PRIVATE ${lib})
    add_test(NAME ${test} COMMAND ${test})
endfunction()

# configure target
function(cf_configure_target target enable_exceptions pch enable_ser)
    # exceptions
    if(NOT enable_exceptions)
        if(MSVC)
            target_compile_options(${target} PRIVATE /EHs- /D_HAS_EXCEPTIONS=0)
        else()
            target_compile_options(${target} PRIVATE -fno-exceptions)
        endif()
    endif()

    # PCH
    if(ENABLE_PCH AND NOT "${target}" STREQUAL "cflib_base")
        if(pch)
            target_precompile_headers(${target} PRIVATE ${pch})
        else()
            target_precompile_headers(${target} REUSE_FROM cflib_base)
        endif()
    endif()

    # autogenerated serialization
    if(enable_ser)
        # get header files
        get_target_property(headers ${target} SOURCES)
        list(FILTER headers INCLUDE REGEX "\.h$")

        # filter by containing of SERIALIZE_CLASS
        set(DAO_HEADERS)
        set(RMI_SERVICE_HEADERS)
        foreach(header ${headers})
            file(STRINGS "${header}" lines REGEX "SERIALIZE_CLASS|^[ \t]*CFPerm[ \t]+")
            if(NOT lines)
                list(REMOVE_ITEM headers "${header}")
                continue()
            endif()

            # check for service or dao
            cmake_path(APPEND CMAKE_CURRENT_SOURCE_DIR "${header}" OUTPUT_VARIABLE header_full_path)
            file(STRINGS "${header}" lines REGEX "RMIService")
            if(lines)
                list(APPEND RMI_SERVICE_HEADERS "${header_full_path}")
            else()
                list(APPEND DAO_HEADERS "${header_full_path}")
            endif()
        endforeach()

        # Something to do?
        if(NOT headers)
            return()
        endif()

        # store found headers
        if(DAO_HEADERS)
            set_target_properties(${target} PROPERTIES DAO_HEADERS "${DAO_HEADERS}")
        endif()
        if(RMI_SERVICE_HEADERS)
            set_target_properties(${target} PROPERTIES RMI_SERVICE_HEADERS "${RMI_SERVICE_HEADERS}")
        endif()

        foreach(header ${headers})
            # get output filename (dir/header.h -> target_autogen/dir/header_ser.cpp)
            set(rel_dir "${target}_autogen")
            get_filename_component(dir "${header}" DIRECTORY)
            if(dir)
                set(rel_dir "${rel_dir}/${dir}")
            endif()
            get_filename_component(source "${header}" NAME_WLE)
            set(source "${rel_dir}/${source}_ser.cpp")

            # add generation step
            add_custom_command(
                OUTPUT "${source}"
                COMMAND ${CMAKE_COMMAND} -E make_directory "${rel_dir}"
                COMMAND ser serialize "${CMAKE_CURRENT_SOURCE_DIR}/${header}" "${source}"
                DEPENDS ser "${header}"
                VERBATIM
            )
            target_sources(${target} PRIVATE "${source}")
        endforeach()
    endif()

    # resources
    if(ARGN)
        add_library(${target}_resources OBJECT)
        target_link_libraries(${target}_resources PRIVATE cflib_base)
        target_link_libraries(${target} PUBLIC ${target}_resources)
        foreach(resource ${ARGN})
            # get output filename (dir/resource.bin -> target_autogen/dir/resource.bin_rc.cpp)
            set(rel_dir "${CMAKE_CURRENT_BINARY_DIR}/${target}_autogen")
            get_filename_component(dir "${resource}" DIRECTORY)
            if(dir)
                set(rel_dir "${rel_dir}/${dir}")
            endif()
            set(source "${rel_dir}/${resource}_rc.cpp")

            # add generation step
            add_custom_command(
                OUTPUT "${source}"
                WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
                COMMAND ${CMAKE_COMMAND} -E make_directory "${rel_dir}"
                COMMAND bin2src "${resource}" "${source}"
                DEPENDS bin2src "${resource}"
                VERBATIM
            )
            target_sources(${target}_resources PUBLIC "${source}")
        endforeach()
    endif()
endfunction()

# API generation
function(cf_handle_args_dao_remote_apis link_target api_name)
    # dao as lib
    if(ARG_DAO)
        cf_find_sources(sources ${ARG_DAO})
        if(ONLY_GENERATORS)
            add_library(${api_name}_dao EXCLUDE_FROM_ALL ${sources})
        else()
            add_library(${api_name}_dao ${sources})
        endif()
        cf_configure_target(${api_name}_dao FALSE "" TRUE)
        target_include_directories(${api_name}_dao PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
        target_link_libraries(${api_name}_dao PUBLIC cflib_dao cflib_serialize)
        target_link_libraries(${link_target} PUBLIC ${api_name}_dao)
    endif()

    # remote APIs
    if(NOT ARG_REMOTE_APIS)
        return()
    endif()

    # collect all RMI_HEADERS
    set(RMI_HEADERS)
    cf_get_dependent_targets(${link_target} DEP_TARGETS)
    foreach(dep_target IN LISTS DEP_TARGETS)
        get_target_property(dep_headers ${dep_target} DAO_HEADERS)
        if(NOT dep_headers STREQUAL "dep_headers-NOTFOUND")
            list(APPEND RMI_HEADERS ${dep_headers})
        endif()
    endforeach()

    # parse DEST from parameters
    set(REMOTE_DIR)
    set(REMOTE_APIS)
    set(RMI_SERVICE_TARGETS)
    set(found_DEST FALSE)
    set(found_FOR FALSE)
    foreach(part IN LISTS ARG_REMOTE_APIS)
        if(part STREQUAL "DEST")
            set(found_FOR FALSE)
            set(found_DEST TRUE)
            if(REMOTE_APIS)
                cf_generate_api()
                set(REMOTE_APIS)
                set(RMI_SERVICE_TARGETS)
            endif()
            continue()
        elseif(part STREQUAL "FOR")
            set(found_FOR TRUE)
            continue()
        elseif(part STREQUAL "TYPES")
            set(found_FOR FALSE)
            continue()
        endif()

        if(found_DEST)
            set(found_DEST FALSE)
            set(REMOTE_DIR "${part}")
            continue()
        endif()
        if(found_FOR)
            list(APPEND RMI_SERVICE_TARGETS ${part})
        else()
            list(APPEND REMOTE_APIS ${part})
        endif()
    endforeach()
    if(REMOTE_APIS)
        cf_generate_api()
    endif()
endfunction()

function(cf_generate_api)
    if(NOT REMOTE_DIR)
        message(FATAL_ERROR "No destination for REMOTE_APIS specified.")
    endif()

    if(NOT RMI_SERVICE_TARGETS)
        set(RMI_SERVICE_TARGETS ${link_target})
    endif()

    foreach(target ${RMI_SERVICE_TARGETS})
        get_target_property(RMI_SERVICE_HEADERS ${target} RMI_SERVICE_HEADERS)
        list(APPEND RMI_HEADERS ${RMI_SERVICE_HEADERS})
    endforeach()

    # set REMOTE_ABS_DIR
    cmake_path(APPEND CMAKE_CURRENT_SOURCE_DIR "${REMOTE_DIR}" OUTPUT_VARIABLE REMOTE_ABS_DIR)

    # version.md will always be generated
    set(output)
    cmake_path(APPEND REMOTE_ABS_DIR version.md OUTPUT_VARIABLE version_full_path)
    list(APPEND output "${version_full_path}")

    if(cpp IN_LIST REMOTE_APIS)
        # add ::services lib
        if(ONLY_GENERATORS)
            add_library(${api_name}_services EXCLUDE_FROM_ALL)
        else()
            add_library(${api_name}_services)
        endif()
        add_library(${api_name}::services ALIAS ${api_name}_services)
        target_include_directories(${api_name}_services PUBLIC "${REMOTE_ABS_DIR}/cpp")
        target_link_libraries(${api_name}_services PUBLIC cflib_net)
        if(ARG_DAO)
            target_link_libraries(${api_name}_services PUBLIC ${api_name}_dao)
        endif()

        # add cpp output files
        foreach(target ${RMI_SERVICE_TARGETS})
            get_target_property(RMI_SERVICE_HEADERS ${target} RMI_SERVICE_HEADERS)
            get_target_property(TARGET_SOURCE_DIR   ${target} INTERFACE_INCLUDE_DIRECTORIES)
            if(TARGET_SOURCE_DIR STREQUAL "TARGET_SOURCE_DIR-NOTFOUND")
                get_target_property(TARGET_SOURCE_DIR ${target} SOURCE_DIR)
            endif()
            foreach(header ${RMI_SERVICE_HEADERS})
                # remove .h
                get_filename_component(dir  "${header}" DIRECTORY)
                get_filename_component(file "${header}" NAME_WLE )
                file(RELATIVE_PATH dir "${TARGET_SOURCE_DIR}" "${dir}")
                set(file "${dir}/${file}")

                list(APPEND output
                    "${REMOTE_ABS_DIR}/cpp/remote/${file}.h"
                    "${REMOTE_ABS_DIR}/cpp/remote/${file}.cpp"
                )
                target_sources(${api_name}_services
                    PUBLIC  "${REMOTE_DIR}/cpp/remote/${file}.h"
                    PRIVATE "${REMOTE_DIR}/cpp/remote/${file}.cpp"
                )
            endforeach()
        endforeach()
    else()
        string(MAKE_C_IDENTIFIER "${api_name}_${REMOTE_DIR}_api" target)
        if(ONLY_GENERATORS)
            add_custom_target(${target} EXCLUDE_FROM_ALL DEPENDS ${output})
        else()
            add_custom_target(${target} ALL DEPENDS ${output})
        endif()
    endif()

    # format type parameters
    set(output_types)
    foreach(type ${REMOTE_APIS})
        list(APPEND output_types -t ${type})
    endforeach()

    # git hash
    cf_git_version(GIT_HASH)
    if(NOT "${GIT_HASH}" STREQUAL "")
        set(GIT_HASH --git ${GIT_HASH})
    endif()

    # command
    add_custom_command(
        OUTPUT ${output}
        COMMAND apiexporter --dest "${REMOTE_ABS_DIR}" ${GIT_HASH} --name ${api_name} ${output_types} ${RMI_HEADERS}
        DEPENDS apiexporter ${RMI_HEADERS}
        VERBATIM
    )
endfunction()
