#
# __find_headers( target headers )
#
function(__find_headers target headers)

    get_target_property(dir ${target} SOURCE_DIR)

    file(GLOB_RECURSE findings
        CONFIGURE_DEPENDS
        RELATIVE ${dir}
        *.h
    )

    set(headers ${findings} PARENT_SCOPE)

endfunction(__find_headers)

#
# __filter_serializeable_headers( headers )
#
function(__filter_serializeable_headers headers)

    set(findings)

    foreach(header ${headers})
        file(STRINGS ${header} lines REGEX "SERIALIZE_CLASS")
        if(lines)
            message("Found autogeneration candidate ${header}")
            list(APPEND findings ${header})
        endif()
    endforeach()

    set(headers ${findings} PARENT_SCOPE)

endfunction(__filter_serializeable_headers)

#
# __generate_implementations( target headers )
#
function(__generate_implementations target headers)

    get_target_property(binary_dir ${target} BINARY_DIR)
    get_target_property(source_dir ${target} SOURCE_DIR)

    set(target_folder ${binary_dir}/autogenerated)
    set(files)

    file(MAKE_DIRECTORY ${target_folder})

    foreach(header ${headers})
        string(REPLACE "/" "_" file_stem ${header})
        string(REPLACE ".h" "" file_stem ${file_stem})
        set(file ${target_folder}/${file_stem}_ser.cpp)
        add_custom_command(
            OUTPUT     ${file}
            COMMAND    ser serialize ${source_dir}/${header} ${file}
            COMMENT    "Generate implementation for ${header}"
            DEPENDS    ${source_dir}/${header}
            VERBATIM
        )
        list(APPEND files ${file})
    endforeach()

    target_sources(${target}
        PRIVATE ${files}
    )

endfunction()

#
# generate_implementations_for( TARGET target )
#
function(generate_implementations_for)

    cmake_parse_arguments(_ "" "TARGET" "" ${ARGN})

    __find_headers(${__TARGET} headers)

    __filter_serializeable_headers("${headers}")

    __generate_implementations(${__TARGET} "${headers}")

endfunction(generate_implementations_for)
